import os
import time
import subprocess
import logging
from typing import Dict, Any, Optional
from docx import Document
from docx.shared import Inches, Pt, RGBColor

logger = logging.getLogger("docs_notepad_tool")


class DocsNotepadTool:
    """Handles note taking in Notepad, Word document creation, and VS Code code generation."""

    def __init__(self, notes_dir: str = "notes", docs_dir: str = "documents", code_dir: str = "workspace"):
        self.notes_dir = os.path.abspath(notes_dir)
        self.docs_dir = os.path.abspath(docs_dir)
        self.code_dir = os.path.abspath(code_dir)

        os.makedirs(self.notes_dir, exist_ok=True)
        os.makedirs(self.docs_dir, exist_ok=True)
        os.makedirs(self.code_dir, exist_ok=True)

    # ==================== NOTEPAD NOTE-TAKING ====================

    def take_note(self, text: str, filename: Optional[str] = None, open_editor: bool = True) -> Dict[str, Any]:
        """Saves text/dictation to a note file and opens it in Notepad."""
        if not filename:
            filename = f"note_{int(time.time())}.txt"
        elif not filename.endswith(".txt"):
            filename += ".txt"

        file_path = os.path.join(self.notes_dir, filename)
        logger.info(f"Saving note to {file_path}...")

        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(text)

            if open_editor:
                subprocess.Popen(["notepad.exe", file_path])
                logger.info("Notepad opened with note.")

            return {
                "success": True,
                "file_path": file_path,
                "filename": filename,
                "message": f"Note saved to '{filename}' and opened in Notepad, Sir.",
            }
        except Exception as e:
            logger.error(f"Failed to create note: {e}")
            return {"success": False, "error": str(e)}

    # ==================== MICROSOFT WORD DOCUMENT GENERATION ====================

    def create_word_document(self, title: str, content: str, filename: Optional[str] = None, open_word: bool = True) -> Dict[str, Any]:
        """Creates a beautifully formatted .docx Word document and opens it in Microsoft Word."""
        if not filename:
            clean_title = "".join(c for c in title if c.isalnum() or c in (" ", "_", "-")).strip().replace(" ", "_")
            filename = f"{clean_title[:30]}_{int(time.time())}.docx"
        elif not filename.endswith(".docx"):
            filename += ".docx"

        file_path = os.path.join(self.docs_dir, filename)
        logger.info(f"Generating Word document at {file_path}...")

        try:
            doc = Document()
            
            # Title
            title_p = doc.add_heading(title, level=0)
            
            # Subtitle / Timestamp
            sub = doc.add_paragraph()
            sub_run = sub.add_run(f"Generated by J.A.R.V.I.S. • {time.ctime()}")
            sub_run.font.italic = True
            sub_run.font.size = Pt(9)
            sub_run.font.color.rgb = RGBColor(120, 120, 120)
            doc.add_paragraph() # Spacer

            # Parse sections and bullet points
            lines = content.split("\n")
            for line in lines:
                l = line.strip()
                if not l:
                    continue
                if l.startswith("### "):
                    doc.add_heading(l[4:], level=2)
                elif l.startswith("## "):
                    doc.add_heading(l[3:], level=1)
                elif l.startswith("# "):
                    doc.add_heading(l[2:], level=0)
                elif l.startswith(("- ", "* ", "• ")):
                    doc.add_paragraph(l[2:], style="List Bullet")
                elif l[0].isdigit() and l[1:3] in (". ", ") "):
                    doc.add_paragraph(l[3:], style="List Number")
                else:
                    doc.add_paragraph(l)

            doc.save(file_path)
            logger.info("Word document saved.")

            if open_word:
                try:
                    os.startfile(file_path)
                except Exception as e:
                    subprocess.Popen(["start", file_path], shell=True)

            return {
                "success": True,
                "file_path": file_path,
                "filename": filename,
                "title": title,
                "message": f"Document '{filename}' created and opened in Microsoft Word, Sir.",
            }
        except Exception as e:
            logger.error(f"Word doc generation error: {e}")
            return {"success": False, "error": str(e)}

    def _get_vscode_cmd(self) -> str:
        """Finds the best command or binary path for VS Code."""
        user_bin = os.path.expanduser(r"~\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd")
        user_exe = os.path.expanduser(r"~\AppData\Local\Programs\Microsoft VS Code\Code.exe")
        prog_cmd = r"C:\Program Files\Microsoft VS Code\bin\code.cmd"
        for p in [user_bin, user_exe, prog_cmd]:
            if os.path.exists(p):
                return p
        import shutil
        return shutil.which("code") or "code"

    def generate_code(self, code: str, filename: str, project_dir: Optional[str] = None, open_vscode: bool = True) -> Dict[str, Any]:
        """Writes source code to a file and opens it in Visual Studio Code."""
        target_dir = os.path.abspath(project_dir) if project_dir else self.code_dir
        os.makedirs(target_dir, exist_ok=True)
        file_path = os.path.join(target_dir, filename)

        logger.info(f"Writing code file to {file_path}...")
        try:
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(code)

            if open_vscode:
                vscode_cmd = self._get_vscode_cmd()
                logger.info(f"Launching VS Code with '{vscode_cmd}' on '{file_path}'...")
                try:
                    subprocess.Popen([vscode_cmd, file_path], shell=True)
                except Exception as e:
                    logger.warning(f"Direct VS Code launch failed ({e}), trying shell fallback...")
                    subprocess.Popen(["code", file_path], shell=True)

            return {
                "success": True,
                "file_path": file_path,
                "filename": filename,
                "message": f"Code successfully generated in '{filename}' and opened in VS Code, Sir.",
            }
        except Exception as e:
            logger.error(f"Code generation error: {e}")
            return {"success": False, "error": str(e)}
